sudo: required
dist: trusty

language: php

branches:
  only:
    - 1.x
    - 2.x
  except:
    - master

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
  - redis

addons:
  mariadb: '10.0'
  
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)